### ISSUE TITLE
feat: 검색 API

### ISSUE THREAD

**Issue by HwangSeungHyeon** [doojoo9999/GigaBox#1]
# Description

- 검색어 기능을 구현한다.

---

# Todo

## V1 - Supabase DB를 이용하여 구현
- [ ] 특정 컬럼을 기준으로 LIKE 조건을 통해 검색하는 API 구현
- [ ] 인기 검색어를 저장할 테이블 생성
- [ ] Paging 처리를 통해 검색 API 에서 결과를 페이지 단위로 조회
- [ ] 인기 검색어 조회 API

## V2 - In Memory DB를 이용하여 구현
- [ ] 특정 컬럼을 기준으로 LIKE 조건을 통해 검색하는 API 구현
- [ ] 인기 검색어를 저장할 테이블 생성
- [ ] Paging 처리를 통해 검색 API 에서 결과를 페이지 단위로 조회
- [ ] 인기 검색어 조회 API

---

# ETC
- DB 결정: 
  - Supabase DB를 사용한 이유: 
- In Memory DB 결정: 
  - 결정한 이유
